SET local check_function_bodies = off;

CREATE TABLE "public"."courses" (
  "id"         bigint                   GENERATED ALWAYS AS IDENTITY NOT NULL,
  "faculty_id" bigint                   NOT NULL,
  "name"       text                     NOT NULL,
  "slug"       text                     NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "courses_faculty_id_slug_key" UNIQUE (faculty_id, slug),
  CONSTRAINT "courses_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."courses"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."faculties" (
  "id"         bigint                   GENERATED ALWAYS AS IDENTITY NOT NULL,
  "name"       text                     NOT NULL,
  "short_name" text                     NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  "slug"       text                     NOT NULL,
  CONSTRAINT "faculties_name_key" UNIQUE (name),
  CONSTRAINT "faculties_pkey" PRIMARY KEY (id),
  CONSTRAINT "faculties_short_name_key" UNIQUE (short_name),
  CONSTRAINT "faculties_slug_key" UNIQUE (slug)
);

ALTER TABLE "public"."faculties"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."material_reports" (
  "id"          bigint                   GENERATED ALWAYS AS IDENTITY NOT NULL,
  "material_id" bigint                   NOT NULL,
  "reported_by" uuid                     NOT NULL,
  "reason"      text                     NOT NULL,
  "status"      text                     NOT NULL DEFAULT 'pending'::text,
  "created_at"  timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "material_reports_pkey" PRIMARY KEY (id),
  CONSTRAINT "unique_user_material_report" UNIQUE (material_id, reported_by)
);

ALTER TABLE "public"."material_reports"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."materials" (
  "id"          bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "subject_id"  bigint                   NOT NULL,
  "uploaded_by" uuid,
  "title"       text                     NOT NULL,
  "file_path"   text                     NOT NULL,
  "file_name"   text                     NOT NULL,
  "created_at"  timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "materials_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."materials"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."profiles" (
  "id"                uuid                     NOT NULL,
  "username"          text                     NOT NULL,
  "full_name"         text                     NOT NULL,
  "avatar_url"        text,
  "bio"               text,
  "university"        text                     DEFAULT 'ZUT'::text,
  "semester"          smallint,
  "interests"         text[],
  "github_url"        text,
  "linkedin_url"      text,
  "is_profile_public" boolean                  NOT NULL DEFAULT false,
  "created_at"        timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"        timestamp with time zone NOT NULL DEFAULT now(),
  "faculty_id"        bigint,
  "course_id"         bigint,
  CONSTRAINT "bio_length" CHECK (((bio IS NULL) OR (char_length(bio) <= 500))),
  CONSTRAINT "profiles_pkey" PRIMARY KEY (id),
  CONSTRAINT "profiles_username_key" UNIQUE (username),
  CONSTRAINT "semester_range" CHECK (((semester IS NULL) OR ((semester >= 1) AND (semester <= 14)))),
  CONSTRAINT "username_length" CHECK (((username IS NULL) OR ((char_length(username) >= 3) AND (char_length(username) <= 30))))
);

ALTER TABLE "public"."profiles"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."semesters" (
  "id"         bigint                   GENERATED ALWAYS AS IDENTITY NOT NULL,
  "course_id"  bigint                   NOT NULL,
  "number"     integer                  NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "semesters_course_id_number_key" UNIQUE (course_id, number),
  CONSTRAINT "semesters_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."semesters"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."subject_channels" (
  "id"         bigint                   GENERATED ALWAYS AS IDENTITY NOT NULL,
  "subject_id" bigint                   NOT NULL,
  "label"      text                     NOT NULL,
  "created_at" timestamp with time zone DEFAULT now(),
  CONSTRAINT "subject_channels_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."subject_channels"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."subjects" (
  "id"          bigint                   GENERATED ALWAYS AS IDENTITY NOT NULL,
  "semester_id" bigint                   NOT NULL,
  "name"        text                     NOT NULL,
  "slug"        text                     NOT NULL,
  "created_at"  timestamp with time zone DEFAULT now(),
  CONSTRAINT "subjects_pkey" PRIMARY KEY (id),
  CONSTRAINT "subjects_semester_id_slug_key" UNIQUE (semester_id, slug)
);

ALTER TABLE "public"."subjects"
  ENABLE ROW LEVEL SECURITY;

CREATE TYPE "public"."channel_type" AS ENUM (
  'lecture',
  'lab',
  'exercises'
);

ALTER TABLE "public"."materials"
  ADD COLUMN "channel_type" public.channel_type NOT NULL;

ALTER TABLE "public"."subject_channels"
  ADD COLUMN "type" public.channel_type NOT NULL;

CREATE TYPE "public"."icon_type" AS ENUM (
  'sigma',
  'atom',
  'code',
  'flask'
);

ALTER TABLE "public"."subjects"
  ADD COLUMN "icon" public.icon_type NOT NULL;

CREATE TYPE "public"."theme_type" AS ENUM (
  'sand',
  'blue',
  'ink',
  'violet'
);

ALTER TABLE "public"."subjects"
  ADD COLUMN "theme" public.theme_type NOT NULL;

CREATE OR REPLACE FUNCTION public.handle_new_user()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO ''
  AS $function$begin

  insert into public.profiles (

    id,

    username,

    full_name,

 

    created_at,

    updated_at

  )

  values (

    new.id,

   

    nullif(new.raw_user_meta_data ->> 'username', ''),

    nullif(new.raw_user_meta_data ->> 'full_name', ''),

   

    now(),

    now()

  );

  return new;

end;$function$;

REVOKE ALL ON FUNCTION "public"."handle_new_user"() FROM PUBLIC, "anon", "authenticated";

CREATE OR REPLACE FUNCTION public.set_profile_updated_at()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SET search_path TO ''
  AS $function$

begin

  new.updated_at = now();

  return new;

end;

$function$;

ALTER TABLE "public"."courses"
  ADD CONSTRAINT "courses_faculty_id_fkey" FOREIGN KEY (faculty_id) REFERENCES public.faculties(id) ON DELETE CASCADE;

ALTER TABLE "public"."material_reports"
  ADD CONSTRAINT "material_reports_material_id_fkey" FOREIGN KEY (material_id) REFERENCES public.materials(id) ON DELETE CASCADE;

ALTER TABLE "public"."profiles"
  ADD CONSTRAINT "profiles_courser_id_fkey" FOREIGN KEY (course_id) REFERENCES public.courses(id);

ALTER TABLE "public"."profiles"
  ADD CONSTRAINT "profiles_faculty_id_fkey" FOREIGN KEY (faculty_id) REFERENCES public.faculties(id);

ALTER TABLE "public"."profiles"
  ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE "public"."material_reports"
  ADD CONSTRAINT "material_reports_reported_by_fkey" FOREIGN KEY (reported_by) REFERENCES public.profiles(id) ON DELETE CASCADE;

ALTER TABLE "public"."materials"
  ADD CONSTRAINT "materials_uploaded_by_fkey" FOREIGN KEY (uploaded_by) REFERENCES public.profiles(id) ON DELETE SET NULL;

ALTER TABLE "public"."semesters"
  ADD CONSTRAINT "semesters_course_id_fkey" FOREIGN KEY (course_id) REFERENCES public.courses(id) ON DELETE CASCADE;

ALTER TABLE "public"."subject_channels"
  ADD CONSTRAINT "subject_channels_subject_id_type_key" UNIQUE (subject_id, TYPE);

ALTER TABLE "public"."materials"
  ADD CONSTRAINT "materials_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES public.subjects(id) ON DELETE CASCADE;

ALTER TABLE "public"."subject_channels"
  ADD CONSTRAINT "subject_channels_subject_id_fkey" FOREIGN KEY (subject_id) REFERENCES public.subjects(id) ON DELETE CASCADE;

ALTER TABLE "public"."subjects"
  ADD CONSTRAINT "subjects_semester_id_fkey" FOREIGN KEY (semester_id) REFERENCES public.semesters(id) ON DELETE CASCADE;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

CREATE TRIGGER set_profiles_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.set_profile_updated_at();

CREATE POLICY "authenticated users able to select courses " ON "public"."courses"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "authenticated users able select faculties" ON "public"."faculties"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "authenticated users can add report_material" ON "public"."material_reports"
  FOR INSERT
  TO PUBLIC
  WITH CHECK ((reported_by = auth.uid()));

CREATE POLICY "authenticated users able add materials" ON "public"."materials"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((uploaded_by = auth.uid()));

CREATE POLICY "authenticated users able select material" ON "public"."materials"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "Users can update own profile" ON "public"."profiles"
  FOR UPDATE
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = id))
  WITH CHECK ((( SELECT auth.uid() AS uid) = id));

CREATE POLICY "Users can view own profile" ON "public"."profiles"
  FOR SELECT
  TO "authenticated"
  USING ((( SELECT auth.uid() AS uid) = id));

CREATE POLICY "authenticated users able to select semestr" ON "public"."semesters"
  FOR SELECT
  TO "authenticated"
  USING ((course_id = ( SELECT profiles.course_id
   FROM public.profiles
  WHERE (profiles.id = auth.uid()))));

CREATE POLICY "authenticated users able to selects subject_channels" ON "public"."subject_channels"
  FOR SELECT
  TO "authenticated"
  USING (true);

CREATE POLICY "authenticated users able to selects subjects " ON "public"."subjects"
  FOR SELECT
  TO PUBLIC
  USING (true);

CREATE POLICY "Authenticated users can upload to subjects" ON "storage"."objects"
  FOR INSERT
  TO "authenticated"
  WITH CHECK ((bucket_id = 'materials'::text));

CREATE POLICY "Authenticated users can view subjects files" ON "storage"."objects"
  FOR SELECT
  TO "authenticated"
  USING ((bucket_id = 'materials'::text));

GRANT EXECUTE ON FUNCTION "public"."handle_new_user"() TO "postgres", "service_role";

GRANT EXECUTE ON FUNCTION "public"."set_profile_updated_at"() TO PUBLIC, "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."courses" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."faculties" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."material_reports" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."materials" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."profiles" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."semesters" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."subject_channels" TO "anon", "authenticated", "postgres", "service_role";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."subjects" TO "anon", "authenticated", "postgres", "service_role";

GRANT USAGE ON TYPE "public"."channel_type" TO "postgres";

GRANT USAGE ON TYPE "public"."icon_type" TO "postgres";

GRANT USAGE ON TYPE "public"."theme_type" TO "postgres";

